import type { CoreMlManifest } from "./coremlBuild";
import type { PangramFs } from "./pangramFs";

/**
 * Bundled Core ML skeleton for the ANE engine — generated by
 * scripts/export_pangram_coreml.py from the PUBLIC architecture (the 0.28MB
 * MLProgram carries no Pangram IP; weights are built on-device).
 */

export const COREML_MODEL_MODULE:
  | number
  | null = require("../../assets/models/pangram_coreml.mlmodel");
export const COREML_MANIFEST: CoreMlManifest | null =
  require("../../assets/models/pangram_coreml_manifest.json") as CoreMlManifest;

/** Stage the bundled model.mlmodel into the package dir on device. */
export async function importCoreMlModel(
  fs: PangramFs,
  destName: string,
): Promise<void> {
  if (COREML_MODEL_MODULE == null) throw new Error("coreml asset missing");
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { Asset } = require("expo-asset") as typeof import("expo-asset");
  const asset = Asset.fromModule(COREML_MODEL_MODULE);
  await asset.downloadAsync();
  if (!asset.localUri) throw new Error("coreml asset has no local uri");
  await fs.importFile(asset.localUri, destName);
}
