import { createMMKV } from "react-native-mmkv";

import {
  fetchRepoInfo,
  fileUrl,
  hubAuthHeaders,
  REQUIRED_FILES,
  type HubFetch,
} from "./pangramHub";
import type { PangramFs } from "./pangramFs";
import {
  parseSafetensorsHeader,
  validatePangramCheckpoint,
  SAFETENSORS_PROBE_BYTES,
  type SafetensorsIndex,
} from "./safetensors";

/**
 * Open Pangram model lifecycle: download the gated checkpoint with the
 * user's HF token, verify it really is the RoBERTa classifier, then
 * "rehydrate" — splice the checkpoint's tensors into the external-data file
 * of a weight-free ONNX graph we build from the *public* roberta-large
 * architecture. The app ships zero gated bytes; the graph carries no Pangram
 * IP; the user's download is what makes it a detector.
 *
 * Phases:  none → downloading → downloaded → preparing → ready
 * ("downloaded" persists when the graph asset isn't bundled in this build —
 * the checkpoint is kept so a later build can finish the job.)
 */

export const PANGRAM_FILES = {
  config: "config.json",
  vocab: "vocab.json",
  merges: "merges.txt",
  weights: "model.safetensors",
  graph: "pangram_graph.onnx",
  data: "pangram_weights.data",
} as const;

export type PangramPhase =
  | "none"
  | "downloading"
  | "downloaded"
  | "preparing"
  | "ready"
  | "error";

export interface PangramState {
  phase: PangramPhase;
  /** Repo revision the install is pinned to. */
  sha?: string;
  numLabels?: number;
  /** Class names from the checkpoint's config.json id2label, index-ordered. */
  labels?: string[];
  weightsBytes?: number;
  updatedAt?: number;
  error?: string;
}

const store = createMMKV({ id: "janus.pangram.v1" });
const KEY = "state";
const listeners = new Set<(s: PangramState) => void>();

export function getPangramState(): PangramState {
  try {
    const raw = store.getString(KEY);
    return raw ? (JSON.parse(raw) as PangramState) : { phase: "none" };
  } catch {
    return { phase: "none" };
  }
}

export function setPangramState(patch: Partial<PangramState>): PangramState {
  const next = { ...getPangramState(), ...patch, updatedAt: Date.now() };
  if (patch.phase && patch.phase !== "error") next.error = undefined;
  try {
    store.set(KEY, JSON.stringify(next));
  } catch {
    /* best-effort */
  }
  listeners.forEach((fn) => fn(next));
  return next;
}

export function subscribePangram(fn: (s: PangramState) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

/* ------------------------------------------------------------------ */
/* Rehydration manifest (generated by scripts/export_pangram_graph.py) */
/* ------------------------------------------------------------------ */

export interface RehydrationManifest {
  version: 1;
  numLabels: number;
  /** Size the weights data file must reach. */
  dataTotalBytes: number;
  /** Where each checkpoint tensor's raw bytes land in the data file. */
  tensors: { name: string; dstOffset: number; bytes: number }[];
}

export interface CopyOp {
  srcOffset: number;
  dstOffset: number;
  bytes: number;
}

/**
 * Map every manifest tensor onto the downloaded checkpoint. Pure planning —
 * mismatched names, dtypes, or sizes fail here, before any bytes move.
 */
export function planRehydration(
  manifest: RehydrationManifest,
  index: SafetensorsIndex,
): CopyOp[] {
  const ops: CopyOp[] = [];
  for (const t of manifest.tensors) {
    const entry =
      index.tensors[t.name] ??
      index.tensors[t.name.replace(/^roberta\./, "")] ??
      index.tensors[`roberta.${t.name}`];
    if (!entry)
      throw new Error(`rehydrate: checkpoint is missing tensor "${t.name}"`);
    if (entry.dtype !== "F32")
      throw new Error(
        `rehydrate: tensor "${t.name}" is ${entry.dtype}, expected F32`,
      );
    const srcBytes = entry.offsets[1] - entry.offsets[0];
    if (srcBytes !== t.bytes)
      throw new Error(
        `rehydrate: tensor "${t.name}" is ${srcBytes} bytes, manifest expects ${t.bytes}`,
      );
    ops.push({
      srcOffset: index.dataStart + entry.offsets[0],
      dstOffset: t.dstOffset,
      bytes: t.bytes,
    });
  }
  return ops.sort((a, b) => a.dstOffset - b.dstOffset);
}

/* -------------------------------------------------- */
/* Install: download → verify → (optionally) prepare  */
/* -------------------------------------------------- */

export interface InstallDeps {
  token: string;
  fs: PangramFs;
  fetchImpl: HubFetch;
  /**
   * Bundled graph asset loader; resolves null in builds that don't carry the
   * exported graph yet (see scripts/export_pangram_graph.py).
   */
  loadGraph?: () => Promise<{ manifest: RehydrationManifest } | null>;
  onProgress?: (note: string, fraction: number) => void;
}

/** Read labels from the checkpoint's config.json (id2label), if present. */
export function labelsFromConfig(configJson: string): string[] | null {
  try {
    const cfg = JSON.parse(configJson) as {
      id2label?: Record<string, string>;
    };
    if (!cfg.id2label) return null;
    const entries = Object.entries(cfg.id2label)
      .map(([k, v]) => [Number(k), v] as const)
      .sort((a, b) => a[0] - b[0]);
    if (!entries.length || entries.some(([k]) => Number.isNaN(k))) return null;
    return entries.map(([, v]) => v);
  } catch {
    return null;
  }
}

export async function installPangram(deps: InstallDeps): Promise<PangramState> {
  const { token, fs, fetchImpl, onProgress } = deps;
  try {
    setPangramState({ phase: "downloading" });
    onProgress?.("Checking access…", 0);
    const info = await fetchRepoInfo(token, fetchImpl);
    await fs.ensureDir();

    const headers = hubAuthHeaders(token);
    for (let i = 0; i < REQUIRED_FILES.length; i++) {
      const name = REQUIRED_FILES[i];
      const isWeights = name === "model.safetensors";
      onProgress?.(`Downloading ${name}…`, isWeights ? 0 : i / 10);
      await fs.downloadFile(
        fileUrl(info.sha, name),
        name,
        headers,
        isWeights
          ? (written, total) =>
              onProgress?.(
                `Downloading weights (${Math.round(written / 1e6)} MB)…`,
                total > 0 ? written / total : 0,
              )
          : undefined,
      );
    }

    onProgress?.("Verifying checkpoint…", 0.98);
    const probe = await fs.readBytes(
      PANGRAM_FILES.weights,
      0,
      Math.min(
        SAFETENSORS_PROBE_BYTES,
        fs.fileSize(PANGRAM_FILES.weights) ?? SAFETENSORS_PROBE_BYTES,
      ),
    );
    const index = parseSafetensorsHeader(probe);
    const { numLabels } = validatePangramCheckpoint(index);
    const labels =
      labelsFromConfig(await fs.readText(PANGRAM_FILES.config)) ?? undefined;

    setPangramState({
      phase: "downloaded",
      sha: info.sha,
      numLabels,
      labels,
      weightsBytes: fs.fileSize(PANGRAM_FILES.weights) ?? undefined,
    });
    return preparePangram(deps, index);
  } catch (e) {
    setPangramState({
      phase: "error",
      error: e instanceof Error ? e.message : String(e),
    });
    throw e;
  }
}

/**
 * Build the engine's weights file from the downloaded checkpoint. Separate
 * from install so a build that gains the graph asset later can finish a
 * previously downloaded checkpoint without re-downloading 1.4 GB.
 */
export async function preparePangram(
  deps: Pick<InstallDeps, "fs" | "loadGraph" | "onProgress">,
  preparsed?: SafetensorsIndex,
): Promise<PangramState> {
  const { fs, loadGraph, onProgress } = deps;
  const graph = loadGraph ? await loadGraph() : null;
  if (!graph) {
    // Checkpoint stays installed; engine just isn't runnable in this build.
    return setPangramState({ phase: "downloaded" });
  }
  try {
    setPangramState({ phase: "preparing" });
    const index =
      preparsed ??
      parseSafetensorsHeader(
        await fs.readBytes(
          PANGRAM_FILES.weights,
          0,
          Math.min(
            SAFETENSORS_PROBE_BYTES,
            fs.fileSize(PANGRAM_FILES.weights) ?? SAFETENSORS_PROBE_BYTES,
          ),
        ),
      );
    const ops = planRehydration(graph.manifest, index);
    const total = ops.reduce((n, op) => n + op.bytes, 0);
    let done = 0;
    for (const op of ops) {
      await fs.copyRange(
        PANGRAM_FILES.weights,
        PANGRAM_FILES.data,
        op.srcOffset,
        op.dstOffset,
        op.bytes,
      );
      done += op.bytes;
      onProgress?.("Preparing model…", total > 0 ? done / total : 1);
    }
    return setPangramState({ phase: "ready" });
  } catch (e) {
    setPangramState({
      phase: "error",
      error: e instanceof Error ? e.message : String(e),
    });
    throw e;
  }
}

export async function uninstallPangram(fs: PangramFs): Promise<PangramState> {
  await fs.deleteAll();
  return setPangramState({
    phase: "none",
    sha: undefined,
    numLabels: undefined,
    labels: undefined,
    weightsBytes: undefined,
  });
}
